version: '3'
services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
  davical:
    image: fintechstudios/davical
    build: .
    ports:
      - '4080:80'
    volumes:
      - ./config.php:/etc/davical/config.php
    depends_on:
      - postgres
    environment:
      PGHOST: 'postgres'
      PGPASSWORD: 'davical'
      # the following is only needed to run database migrations
      RUN_MIGRATIONS_AT_STARTUP: 'true'
      ROOT_PGUSER: 'postgres'
      ROOT_PGPASSWORD: 'postgres'
      DAVICAL_ADMIN_PASS: 'admin'
